app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SelectField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, Regexp, ValidationError

from ..models import Role, User


class EditProfileAdministratorForm(FlaskForm):
    """
    Form for administrators to edit user profiles
    Rendered by wtf.render_form()
    """
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField('Username',
                           validators=[DataRequired(),
                                       Length(1, 64),
                                       Regexp(
                                           '^[A-Za-z][A-Za-z0-9_.]*$',
                                           0,
                                           'Usernames must have only letters, numbers, dots or underscores')])
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdministratorForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name) for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already in use.')

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')


class EditProfileForm(FlaskForm):
    """
    Form for users edit their profile
    Rendered by render_form()
    """
    name = StringField('Name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About Me')
    submit = SubmitField()

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views
from ..models import Permission
from .. import photos


@users.app_context_processor
def inject_permissions():
    """Make Permissions available to template engine"""
    return dict(Permission=Permission, photos=photos)

app/users/views.py
from flask import current_app, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required
from typing import Final

from . import users
from .forms import EditProfileAdministratorForm, EditProfileForm
from .. import db
from ..main.forms import SearchForm
from ..decorators import admin_required, permission_required
from ..models import Permission, Role, Trade, User

INDEX: Final = '.index'
INVALID_USER: Final = 'Invalid user.'
USER_PROFILE: Final = '.user_profile'


@users.route('/edit-profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    search_form = SearchForm()
    edit_user = User.query.get_or_404(user_id)
    form = EditProfileAdministratorForm(user=edit_user)
    if form.validate_on_submit():
        edit_user.about_me = form.about_me.data
        edit_user.confirmed = form.confirmed.data
        edit_user.email = form.email.data
        edit_user.location = form.location.data
        edit_user.name = form.name.data
        edit_user.role = Role.query.get(form.role.data)
        edit_user.username = form.username.data
        db.session.add(edit_user)
        db.session.commit()
        flash('Profile for ' + edit_user.username + ' updated successfully.')
        return redirect(url_for(USER_PROFILE, username=edit_user.username, search_form=search_form))
    form.about_me.data = edit_user.about_me
    form.confirmed.data = edit_user.confirmed
    form.email.data = edit_user.email
    form.location.data = edit_user.location
    form.name.data = edit_user.name
    form.role.data = edit_user.role_id
    form.username.data = edit_user.username
    return render_template('users/edit_profile.html', form=form, user=edit_user, search_form=search_form)


@users.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    search_form = SearchForm()
    form = EditProfileForm()
    if form.validate_on_submit():
        # Save submitted form
        current_user.about_me = form.about_me.data
        current_user.location = form.location.data
        current_user.name = form.name.data
        db.session.add(current_user)
        db.session.commit()
        flash('Profile successfully updated.')
        return redirect(url_for(USER_PROFILE, username=current_user.username, search_form=search_form))
    # Populate form with user data
    form.about_me.data = current_user.about_me
    form.location.data = current_user.location
    form.name.data = current_user.name
    return render_template('users/edit_profile.html', form=form, search_form=search_form)


@users.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    search_form = SearchForm()
    user = User.find_first_by_username(username=username)
    if user is None:
        flash(INVALID_USER)
        return redirect(url_for(INDEX, search_form=search_form))
    if current_user.is_following(user):
        flash('Already following user.')
        return redirect(url_for(USER_PROFILE, username=username, search_form=search_form))
    current_user.follow(user)
    db.session.commit()
    flash('You are now following %s.' % username)
    return redirect(url_for(USER_PROFILE, username=username, search_form=search_form))


@users.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    search_form = SearchForm()
    user = User.find_first_by_username(username=username)
    if user is None:
        flash(INVALID_USER)
        return redirect(url_for(INDEX, search_form=search_form))
    if not current_user.is_following(user):
        flash('Not following user.')
        return redirect(url_for(USER_PROFILE, username=username, search_form=search_form))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following %s anymore.' % username)
    return redirect(url_for(USER_PROFILE, username=username, search_form=search_form))


@users.route('/followers/<username>')
@login_required
def followers(username):
    search_form = SearchForm()
    user = User.find_first_by_username(username=username)
    if user is None:
        flash(INVALID_USER)
        return redirect(url_for(INDEX, search_form=search_form))
    pagination = user.get_followers_pagination(request)
    follows = [{'user': item.follower, 'timestamp': item.timestamp} for item in pagination.items]
    return render_template('users/followers.html',
                           user=user,
                           title="Followers of",
                           endpoint='.followers',
                           pagination=pagination,
                           follows=follows, search_form=search_form)


@users.route('/followed_by/<username>')
@login_required
def followed_by(username):
    search_form = SearchForm()
    user = User.find_first_by_username(username=username)
    if user is None:
        flash(INVALID_USER)
        return redirect(url_for(INDEX, search_form=search_form))
    pagination = user.get_followed_pagination(request)
    follows = [{'user': item.followed, 'timestamp': item.timestamp} for item in pagination.items]
    return render_template('users/followers.html',
                           user=user,
                           title="Followed by",
                           endpoint='.followed_by',
                           pagination=pagination,
                           follows=follows, search_form=search_form)


@users.route('/watchlist/')
@login_required
def watchlist():
    search_form = SearchForm()
    page = request.args.get('page', 1, type=int)
    pagination = current_user.watches.paginate(page, per_page=current_app.config['WATCHLIST_PER_PAGE'], error_out=False)
    watches = [{'stock': item.stock, 'timestamp': item.timestamp} for item in pagination.items]
    return render_template('users/watchlist.html',
                           user=current_user,
                           title='Watchlist',
                           endpoint='.watchlist',
                           pagination=pagination,
                           watches=watches, search_form=search_form)


@users.route('/<username>')
@login_required
def user_profile(username):
    search_form = SearchForm()
    user = User.find_by_username_or_404(username=username)
    trades = user.trades.order_by(Trade.timestamp.desc()).all()
    return render_template('users/user_profile.html', user=user, trades=trades, search_form=search_form)

app/templates/users/_user_card.html
<div class="card mb-3">
    <div class="row">
        <div class="col-sm-3">
            <div class="card-body">
                <img class="card-img img-thumbnail" src="{{ user.gravatar(size=256) }}" alt="User avatar">
            </div>
        </div>
        <div class="col-sm-9">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('users.user_profile', username=user.username) }}">{{ user.username }}</a></h5>
                <p class="card-text">${{ user.name}}</p>
                <p class="card-text">{{ user.location }}</p>
                <p class="card-text"># of trades{{ user.trades.count() }}</p>
            </div>
        </div>
    </div>
    <div class="card-footer">
        {% if current_user.is_administrator() %}
            <a href="{{ url_for('users.edit_profile', username=user.username) }}">
                <span class="label label-danger">Edit [Admin]</span>
            </a>
        {% endif %}
    </div>
</div>

app/templates/users/_users.html
<ul class="trades">
    {% for user in users %}
        {% include 'users/_user_card.html' %}
    {% endfor %}
</ul>

app/templates/users/edit_profile.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Greek Gang Terminal - Edit Profile{% endblock %}

{% block page_header %}Edit Profile{% endblock %}
{% block page_content %}
    <div class="col-md-4">
        {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/users/followers.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Greek Gang Terminal - {{ title }} {{ user.username }}{% endblock %}
{% block page_header %}{{ title }} {{ user.username }}{% endblock %}
{% block page_content %}
    <p></p>
    <table class="table table-hover followers" aria-label="{{ title }} {{ user.username }}">
        <thead><tr><th scope="col">User</th><th scope="col">Since</th></tr></thead>
        {% for follow in follows %}
            {% if follow.user != user %}
                <tr>
                    <td>
                        <a href="{{ url_for('.user_profile', username = follow.user.username) }}">
                            <img class="rounded" src="{{ follow.user.gravatar(size=32) }}" alt="'User avatar">
                            {{ follow.user.username }}
                        </a>
                    </td>
                    <td>{{ moment(follow.timestamp).format('L') }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
    {% if pagination %}
        {{ render_pagination(pagination, endpoint='.index', prev='«', next='»', align='center') }}
    {% endif %}
{% endblock %}

app/templates/users/user_profile.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Greek Gang Terminal - {{ user.username }}{% endblock %}

{% block page_header %}
    <img class="rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}" alt="User avatar">
    <h1>{{ user.username }}</h1>
{% endblock %}
{% block profile_header %}
    <div class="profile-header">
        {% if user.name or user.location %}
            <p>
                {% if user.name %}{{ user.name }}{% endif %}
                {% if user.location %}
                    From <a href="https://maps.google.com/?q={{ user.location }}">{{ user.location }}</a>
                {% endif %}
            </p>
        {% endif %}
        {% if current_user.is_administrator() %}
            <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
            Member since {{ moment(user.member_since).format('L') }}. Last seen {{ moment(user.last_seen).fromNow() }}.
        </p>
        <p>{{ user.trades.count() }} trades</p>
        <p>
            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('.follow', username=user.username) }}" class="btn btn-primary">Follow</a>
                {% else %}
                    <a href="{{ url_for('.unfollow', username=user.username) }}" class="btn btn-secondary">Unfollow</a>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('.followers', username=user.username) }}">Followers: <span class="badge">{{ user.followers.count() - 1 }}</span></a>
            <a href="{{ url_for('.followed_by', username=user.username) }}">Following: <span class="badge">{{ user.followed.count() - 1 }}</span></a>
            {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
                | <span class="label label-default">Follows you</span>
            {% endif %}
        </p>
        <p>
            {% if user == current_user %}
            <a class="btn btn-secondary" href="{{ url_for('.edit_profile') }}">Edit Profile</a>
            {% endif %}
            {% if current_user.is_administrator() %}
            <a class="btn btn-danger" href="{{ url_for('.edit_profile_admin', user_id=user.id) }}">Edit Profile [Admin]</a>
            {% endif %}
        </p>
    </div>
{% endblock %}
{% block page_content %}
    <h3>Trades by {{ user.username }}</h3>
    {% include 'trades/_trades.html' %}
    {% if pagination %}
        {{ render_pagination(pagination, endpoint='.user_profile', prev='«', next='»', align='center', args={'username':user.username}) }}
    {% endif %}
{% endblock %}

app/templates/users/watchlist.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Greek Gang Terminal - {{ title }} {{ user.username }}{% endblock %}
{% block page_header %}{{ title }} {{ user.username }}{% endblock %}
{% block page_content %}
    <table class="table table-hover followers table-responsive-sm" aria-label="{{ title }} {{ user.username }}">
        <thead><tr><th scope="col">Stock</th><th scope="col">Since</th><th scope="col">Delete</th></tr></thead>
        <tbody class="table-striped">
        {% for watch in watches %}
            <tr class="d-table-row">

                <td class="col-3">
                    <a href="{{ url_for('stocks.stock_info', ticker = watch.stock.ticker) }}">
                        <img class="rounded img-thumbnail" src="{{ watch.stock.photo_filename|resize('100x100', format='png') }}" alt="Company logo">
                        {{ watch.stock.name }}
                    </a>
                </td>
                <td class="col-6">{{ moment(watch.timestamp).format('L') }}</td>
                <td class="col-3"><a href="{{ url_for('stocks.unwatch', ticker=watch.stock.ticker) }}" class="btn btn-primary">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    {% if pagination %}
        {{ render_pagination(pagination, endpoint=endpoint, prev='«', next='»', align='center', args={'username':user.username}) }}
    {% endif %}
{% endblock %}