app/trades/forms.py
from flask_wtf import FlaskForm
from wtforms import DecimalField, IntegerField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

from ..models import Stock, User


# noinspection PyMethodMayBeStatic
class BuyStockForm(FlaskForm):
    ticker = StringField('Ticker', validators=[DataRequired(), Length(1, 5)])
    price = DecimalField('Price', validators=[DataRequired()], places=2)
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_price(self, field):
        if field.data < 0:
            raise ValidationError('Price cannot be negative.')

    def validate_quantity(self, field):
        if field.data < 1:
            raise ValidationError('Cannot buy less than 0 shares.')

    def validate_ticker(self, field):
        """TODO: Send email to admin to add stock manually"""
        if not Stock.query.filter_by(ticker=field.data).first():
            raise ValidationError('Stock not in system. An administrator has been notified.')


# noinspection PyMethodMayBeStatic
class EditTradeForm(FlaskForm):
    ticker = StringField('Ticker', validators=[DataRequired(), Length(1, 5)])
    user = StringField('Username', validators=[DataRequired(), Length(1, 64)])
    price = DecimalField('Price', validators=[DataRequired()], places=2)
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_price(self, field):
        if field.data < 0:
            raise ValidationError('Price cannot be negative.')

    def validate_quantity(self, field):
        if field.data < 1:
            raise ValidationError('Cannot buy less than 0 shares.')

    def validate_ticker(self, field):
        """TODO: Send email to admin to add stock manually"""
        if not Stock.query.filter_by(ticker=field.data).first():
            raise ValidationError('Stock not in system. An administrator has been notified.')

    def validate_user(self, field):
        if not User.query.filter_by(username=field.data).first():
            raise ValidationError('User does not exist.')

app/trades/__init__.py
from flask import Blueprint

trades = Blueprint('trades', __name__)

# Import modules here to avoid circular dependencies until after main is defined
from . import views
from ..models import Permission
from .. import photos


@trades.app_context_processor
def inject_permissions():
    """Make Permissions available to template engine"""
    return dict(Permission=Permission, photos=photos)

app/trades/views.py
from flask import abort, current_app, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from . import trades
from .forms import BuyStockForm, EditTradeForm
from .. import db
from ..main.forms import SearchForm
from ..decorators import admin_required
from ..models import Permission, Stock, Trade, User


@trades.route('/edit/<int:trade_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_trade(trade_id):
    search_form = SearchForm()
    trade_object = Trade.query.get_or_404(trade_id)
    form = EditTradeForm(trade=trade_object)
    if form.validate_on_submit():
        trade_object.stock = Stock.query.filter_by(ticker=form.ticker.data).first()
        trade_object.price = form.price.data
        trade_object.quantity = form.quantity.data
        trade_object.user = User.query.filter_by(username=form.user.data).first()
        db.session.add(trade_object)
        db.session.commit()
        flash('Information for Trade #' + str(trade_object.id) + ' updated successfully.')
        return redirect(url_for('.trade', trade_id=trade_id, search_form=search_form))
    form.ticker.data = trade_object.stock.ticker
    form.price.data = trade_object.price
    form.quantity.data = trade_object.quantity
    form.user.data = trade_object.user.username
    return render_template('trades/edit_trade.html', form=form, trade=trade, search_form=search_form)


# noinspection PyProtectedMember
@trades.route('/', methods=['GET', 'POST'])
@login_required
def trades_list():
    search_form = SearchForm()
    form = BuyStockForm()
    if current_user.can(Permission.WRITE) and form.validate_on_submit():
        trade_object = Trade(stock=Stock.query.filter_by(ticker=form.ticker.data).first(),
                             price=form.price.data,
                             quantity=form.quantity.data,
                             user=current_user._get_current_object())
        db.session.add(trade_object)
        db.session.commit()
        return redirect(url_for('.index', search_form=search_form))
    page = request.args.get('page', 1, type=int)
    pagination = Trade.query.order_by(Trade.timestamp.desc()).paginate(
        page,
        per_page=current_app.config['TRADES_PER_PAGE'],
        error_out=False)
    trade_items = pagination.items
    return render_template('index.html', form=form, trades=trade_items, pagination=pagination, search_form=search_form)


@trades.route('/<int:trade_id>')
@login_required
def trade(trade_id):
    search_form = SearchForm()
    trade_object = Trade.query.get_or_404(trade_id)
    return render_template('trades/trade.html', trades=[trade_object], search_form=search_form)



# noinspection PyProtectedMember
@trades.route('/new_stock_trade', methods=['GET', 'POST'])
@login_required
def new_stock_trade():
    form = BuyStockForm()
    search_form = SearchForm()
    if form.validate_on_submit():
        stock = Stock.query.filter_by(ticker=form.ticker.data).first()
        if stock is None:
            abort(404)
        stock_trade = Trade(stock_id=stock.id,
                          user_id=current_user.id,
                          quantity=form.quantity.data,
                          price=form.price.data)
        db.session.add(stock_trade)
        db.session.commit()
        flash('Trade for ' + str(stock_trade.id) + ' created successfully.')
        return redirect(url_for('users.user_profile', username=current_user.username, search_form=search_form))
    return render_template('trades/new_trade.html', form=form, search_form=search_form)

app/templates/trades/_trade_card.html
<div class="card mb-3">
    <div class="row">
        <div class="col-sm-3">
            {% if trade.stock.photo_filename %}
                <div class="card-body">
                <img class="card-img img-thumbnail" src="{{ trade.stock.photo_filename|resize('200x200', format='png') }}" alt="Company logo">
                </div>
            {% endif %}
        </div>
        <div class="col-sm-9">
            <div class="card-body">
                <h5 class="card-title">Trade by <a href="{{ url_for('users.user_profile', username=trade.user.username) }}">{{ trade.user.username }}</a> on <a href="{{ url_for('stocks.stock_info', ticker=trade.stock.ticker) }}">{{ trade.stock.ticker }}</a></h5>
                <p class="card-text">${{ trade.price }}</p>
                <p class="card-text">{{ trade.quantity }} shares</p>
                <p class="card-text"><small class="text-muted">{{ moment(trade.timestamp).fromNow() }}</small></p>
            </div>
        </div>
    </div>
        <div class="card-footer">
        {% if current_user.is_administrator() %}
            <a href="{{ url_for('trades.edit_trade', trade_id=trade.id) }}">
                <span class="label label-danger">Edit [Admin]</span>
            </a>
        {% endif %}
        <a href="{{ url_for('trades.trade', trade_id=trade.id) }}">
            <span class="label label-danger">Permalink</span>
        </a>
    </div>
</div>

app/templates/trades/_trades.html
<ul class="trades">
    {% for trade in trades %}
        {% include 'trades/_trade_card.html' %}
    {% endfor %}
</ul>

app/templates/trades/edit_trade.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Greek Gang Terminal - Edit Trade{% endblock %}
{% block page_header %}Edit Trade{% endblock %}
{% block page_content %}
    <div class="col-md-4">
        {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/trades/new_trade.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block title %}Greek Gang Terminal - {% if trade %}Edit Trade{% else %}New Trade{% endif %}{% endblock %}

{% block page_header %}
    {% if stock %}Edit Trade - {{ trade.id }}{% else %}{% endif %}
{% endblock %}
{% block page_content %}
    <div class="col-md-4">
        {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/trades/trade.html
{% extends "base.html" %}

{% block title %}Greek Gang Terminal - Trade{% endblock %}

{% block page_content %}
{% include 'trades/_trades.html' %}
{% endblock %}