app/stocks/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import BooleanField, DecimalField, FileField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

from .. import photos
from ..models import Stock


class AddStockForm(FlaskForm):
    """
    Form for administrators to add new stock information
    Rendered by wtf.render_form()
    """
    ticker = StringField('Ticker', validators=[DataRequired(), Length(1, 5)])
    name = StringField('Name', validators=[DataRequired(), Length(1, 64)])
    photo = FileField('Logo', validators=[FileAllowed(photos, 'Images only'),
                                          FileRequired('You must add a company logo')])
    sector = StringField('Sector', validators=[DataRequired(), Length(1, 32)])
    year_high = DecimalField('52-Week High', places=2, validators=[DataRequired()])
    year_low = DecimalField('52-Week Low', places=2, validators=[DataRequired()])
    submit = SubmitField('Submit')

    # noinspection PyMethodMayBeStatic
    def validate_ticker(self, field):
        if Stock.query.filter_by(ticker=field.data).first():
            raise ValidationError('Ticker already in use.')

    def validate_year_high(self, field):
        if field.data < 0:
            raise ValidationError('52-Week High cannot be negative.')
        elif field.data < self.year_low.data:
            raise ValidationError('52-Week High cannot be > 52-Week Low.')

    def validate_year_low(self, field):
        if field.data < 0:
            raise ValidationError('52-Week Low cannot be negative.')
        elif field.data > self.year_high.data:
            raise ValidationError('52-Week Low cannot be > 52-Week High.')


class EditStockForm(FlaskForm):
    """
    Form for administrators to edit stock information
    Rendered by wtf.render_form()
    """
    ticker = StringField('Ticker', validators=[DataRequired(), Length(1, 5)])
    name = StringField('Name', validators=[DataRequired(), Length(1, 64)])
    photo = FileField('Logo', validators=[FileAllowed(photos, 'Images only')])
    active = BooleanField('Active')
    sector = StringField('Sector', validators=[DataRequired(), Length(1, 32)])
    year_high = DecimalField('52-Week High', places=2, validators=[DataRequired()])
    year_low = DecimalField('52-Week Low', places=2, validators=[DataRequired()])
    submit = SubmitField('Submit')

    def __init__(self, stock, *args, **kwargs):
        super(EditStockForm, self).__init__(*args, **kwargs)
        self.stock = stock

    def validate_ticker(self, field):
        if field.data != self.stock.ticker and Stock.query.filter_by(ticker=field.data).first():
            raise ValidationError('Ticker already in use.')

    def validate_year_high(self, field):
        if field.data < 0:
            raise ValidationError('52-Week High cannot be negative.')
        elif field.data < self.year_low.data:
            raise ValidationError('52-Week High cannot be > 52-Week Low.')

    def validate_year_low(self, field):
        if field.data < 0:
            raise ValidationError('52-Week Low cannot be negative.')
        elif field.data > self.year_high.data:
            raise ValidationError('52-Week Low cannot be > 52-Week High.')

app/stocks/__init__.py
from flask import Blueprint

stocks = Blueprint('stocks', __name__)

# Import modules here to avoid circular dependencies until after main is defined
from . import views
from ..models import Permission
from .. import photos


@stocks.app_context_processor
def inject_permissions():
    """Make Permissions available to template engine"""
    return dict(Permission=Permission, photos=photos)

app/stocks/views.py
from flask import abort, current_app, render_template, flash, redirect, request, url_for
from flask_login import current_user, login_required
from typing import Final

from . import stocks
from .forms import AddStockForm, EditStockForm
from .. import db, photos
from ..main.forms import SearchForm
from ..decorators import admin_required
from ..models import Stock, Trade

STOCK_INFO: Final = '.stock_info'


@stocks.route('/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_stock():
    search_form = SearchForm()
    form = AddStockForm()
    if form.validate_on_submit():
        new_stock = Stock(ticker=form.ticker.data,
                          name=form.name.data,
                          photo_filename=photos.save(form.photo.data),
                          is_active=form.active.data,
                          sector=form.sector.data,
                          year_high=form.year_high.data,
                          year_low=form.year_low.data)
        db.session.add(new_stock)
        db.session.commit()
        flash('Profile for ' + new_stock.name + ' created successfully.')
        return redirect(url_for(STOCK_INFO, ticker=new_stock.ticker, search_form=search_form))
    return render_template('stocks/edit_stock.html', form=form, search_form=search_form)


@stocks.route('/edit/<ticker>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_stock(ticker):
    search_form = SearchForm()
    stock = Stock.query.filter_by(ticker=ticker).first()
    if stock is None:
        abort(404)
    form = EditStockForm(stock=stock)
    form.photo.data = None
    if form.validate_on_submit():
        stock.ticker = form.ticker.data
        stock.name = form.name.data
        if form.photo.data is not None:
            stock.photo_filename = photos.save(form.photo.data)
        stock.is_active = form.active.data
        stock.sector = form.sector.data
        stock.year_high = form.year_high.data
        stock.year_low = form.year_low.data
        db.session.add(stock)
        db.session.commit()
        flash('Profile for ' + stock.name + ' updated successfully.')
        return redirect(url_for(STOCK_INFO, ticker=stock.ticker, search_form=search_form))
    form.ticker.data = stock.ticker
    form.name.data = stock.name
    form.active.data = stock.is_active
    form.sector.data = stock.sector
    form.year_high.data = stock.year_high
    form.year_low.data = stock.year_low
    return render_template('stocks/edit_stock.html', form=form, stock=stock, search_form=search_form)


@stocks.route('/<ticker>')
@login_required
def stock_info(ticker):
    search_form = SearchForm()
    stock = Stock.query.filter_by(ticker=ticker).first()
    if stock is None:
        abort(404)
    page = request.args.get('page', 1, type=int)
    pagination = stock.trades.order_by(Trade.timestamp.desc()).paginate(
        page,
        per_page=current_app.config['TRADES_PER_PAGE'],
        error_out=False)
    trades = pagination.items
    return render_template('stocks/stock_info.html', stock=stock, trades=trades, pagination=pagination, search_form=search_form)


@stocks.route('/watch/<ticker>')
@login_required
def watch(ticker):
    search_form = SearchForm()
    stock = Stock.query.filter_by(ticker=ticker).first()
    if stock is None:
        flash('Invalid ticker.')
        return redirect(url_for('.index'))
    if current_user.is_watching(stock):
        flash('Already watching stock.')
        return redirect(url_for(STOCK_INFO, ticker=ticker, search_form=search_form))
    current_user.watch(stock)
    db.session.commit()
    flash('You are now watching %s.' % stock.name)
    return redirect(url_for(STOCK_INFO, ticker=ticker, search_form=search_form))


@stocks.route('/unwatch/<ticker>')
@login_required
def unwatch(ticker):
    search_form = SearchForm()
    stock = Stock.query.filter_by(ticker=ticker).first()
    if stock is None:
        flash('Invalid ticker.')
        return redirect(url_for('.index'))
    if not current_user.is_watching(stock):
        flash('Not watching stock.')
        return redirect(url_for(STOCK_INFO, ticker=ticker, search_form=search_form))
    current_user.unwatch(stock)
    db.session.commit()
    flash('You are not watching %s anymore.' % stock.name)
    return redirect(url_for(STOCK_INFO, ticker=ticker, search_form=search_form))


@stocks.route('/viewAllStocks')
@login_required
def view_all_stocks():
    search_form = SearchForm()
    stocks_list = Stock.query.all()
    return render_template('stocks/view_all_stocks.html', stocks=stocks_list, search_form=search_form)

app/templates/stocks/_stock_card.html
<div class="card mb-3">
    <div class="row">
        <div class="col-sm-3">
            {% if stock.photo_filename %}
                <div class="card-body">
                <img class="card-img img-thumbnail" src="{{ stock.photo_filename|resize('200x200', format='png') }}" alt="Company logo">
                </div>
            {% endif %}
        </div>
        <div class="col-sm-9">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('stocks.stock_info', ticker=stock.ticker) }}">{{ stock.ticker }}</a></h5>
                <p class="card-text">${{ stock.name}}</p>
                <p class="card-text">{{ stock.sector }}</p>
            </div>
        </div>
    </div>
            <div class="card-footer">
            {% if current_user.is_administrator() %}
            <a href="{{ url_for('stocks.edit_stock', ticker=stock.ticker) }}">
                <span class="label label-danger">Edit [Admin]</span>
            </a>
        {% endif %}
        </div>
</div>

app/templates/stocks/_stock_row.html
<div class="card mb-3">
    <div class="row">
        <div class="col-sm-3">
            {% if stock.photo_filename %}
                <div class="card-body">
                <img class="card-img img-thumbnail" src="{{ stock.photo_filename|resize('200x200', format='png') }}" alt="Company logo">
                </div>
            {% endif %}
        </div>
        <div class="col-sm-9">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('stocks.stock_info', ticker=stock.ticker) }}">{{ stock.ticker }}</a></h5>
                <p class="card-text">${{ stock.name}}</p>
                <p class="card-text">{{ stock.sector }}</p>
            </div>
        </div>
    </div>
            <div class="card-footer">
            {% if current_user.is_administrator() %}
            <a href="{{ url_for('stocks.edit_stock', ticker=stock.ticker) }}">
                <span class="label label-danger">Edit [Admin]</span>
            </a>
        {% endif %}
        </div>
</div>

app/templates/stocks/_stocks.html
<ul class="trades">
    {% for stock in stocks %}
        {% include 'stocks/_stock_card.html' %}
    {% endfor %}
</ul>

app/templates/stocks/_stocks_table.html
<ul class="trades">
    {% for stock in stocks %}
        {% include 'stocks/_stock_row.html' %}
    {% endfor %}
</ul>

app/templates/stocks/edit_stock.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block title %}Greek Gang Terminal - {% if stock %}Edit Stock{% else %}Add Stock{% endif %}{% endblock %}

{% block page_header %}
    {% if stock %}Edit Stock - {{ stock.name }}{% else %}Add Stock{% endif %}
{% endblock %}
{% block page_content %}
    <div class="col-md-4">
        {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/stocks/stock_info.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Greek Gang Terminal - {{ stock.name }}{% endblock %}

{% block page_header %}
    <div class="col-sm-3">
        {% if stock.photo_filename %}
            <img class="rounded img-thumbnail" src="{{ stock.photo_filename|resize('300x300', format='png') }}" alt="Company Logo">
        {% endif %}
    </div>
{% endblock %}
{% block profile_header %}
    <div class="col-sm-9 right">
        <h3>Trades of {{ stock.name }}</h3>
        <p>{{ stock.sector }}</p>
        <p>
            {% if not current_user.is_watching(stock) %}
                <a href="{{ url_for('.watch', ticker=stock.ticker) }}" class="btn btn-primary">Watch</a>
            {% else %}
                <a href="{{ url_for('.unwatch', ticker=stock.ticker) }}" class="btn btn-primary">Unwatch</a>
            {% endif %}
            {% if current_user.is_administrator() %}
            <a class="btn btn-danger" href="{{ url_for('.edit_stock', ticker=stock.ticker) }}">Edit Stock [Admin]</a>
            {% endif %}
        </p>
    </div>

{% endblock %}
{% block page_content %}
    {% include 'trades/_trades.html' %}
    {% if pagination %}
        {{ render_pagination(pagination, endpoint='.stock_info', prev='«', next='»', align='center', args={'ticker':stock.ticker}) }}
    {% endif %}
{% endblock %}

app/templates/stocks/view_all_stocks.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Greek Gang Terminal - All Stocks{% endblock %}

{% block page_header %}
{% endblock %}
{% block profile_header %}
    <div class="col-sm-9 right">
        <h3>All Stocks Currently Available</h3>
    </div>

{% endblock %}
{% block page_content %}
    {% include 'stocks/_stocks_table.html' %}
    {% if pagination %}
        {{ render_pagination(pagination, endpoint='.view_all_stocks', prev='«', next='»', align='center', args={'':''}) }}
    {% endif %}
{% endblock %}